name: Build, Test and Deploy to Github Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{secrets.USERNAME}}
        git remote set-url origin https://${{secrets.TOKEN}}@github.com/${{secrets.USERNAME}}/course-testing-js-ts-react-components.git
        npm run deploy
